### ISSUE TITLE
MDT IP interface with KNXd Link down, terminating

### ISSUE THREAD

**Issue by hyperbart** [knxd/knxd#620]
Long time user of KNXd (eibd) and KNXd is a critical component in my home automation as it is responsible to link my bus towards Homebridge for Homekit control of my house.

I have a machine that needs to be lifecycled and currently still runs knxd (older version) on Ubuntu 18.04 LTS.
As I am centralising I want to migrate to knxd running in docker on my main server and I am unable to get it working and I hope to get some help here.

My old config consisted of some options, but was quite limited I think:

```
# configuration for knxd.service
KNXD_OPTS="-e 0.0.1 -E 0.0.2:100 -u /tmp/eib -b ipt:192.168.4.154"
```

So after migrating to the knxd running in a docker, my config.ini file I have constructed looks like this:

```
[A.retry]
filter=retry
retry-delay = 5.0
#max-retries = 0
#may-fail = true

[B.tcp]i
server = knxd_tcp
port = 6720

[C.ipt]
driver = ipt
ip-address = 192.168.4.154
dest-port = 3671
filters = A.retry

[debug-main]
error-level = 0x9

[main]
addr = 0.0.1
client-addrs = 0.0.2:8
connections = B.tcp,C.ipt
debug = debug-main
```

You can see above I have commented out the max retries and max-fail to trigger the error message below, which I can't figure out what is going wrong. A similar config with a friend of mine is working fine.

The docker is being deployed via the following deployment file:

```
version: '3.7'

networks:
  thuis:
    name: thuis
    external: true

services:
  knxd:
    #image: tekn0ir/knxd
    image: renehezser/knxd
    container_name: knxd
    volumes:
      - /EVO500/AppsConfig/knxd/config.ini:/config.ini
    ports:
      - 6720:6720
      - 3671:3671
    restart: always
    network_mode: host
```

```
+ USER_ID=9001
+ DOCKER_GID=9002
+ USER_NAME=docker
+ exec /usr/local/bin/gosu 9001:9002 /cmd.sh
+ export HOME=/home/docker
+ knxd /config.ini
I00000131: [ 1:main] 0.14.62: knxd /config.ini
I00000129: [ 1:main] Connected: cfg:C.ipt.
I00000129: [ 1:main] Connected: cfg:B.tcp.
F00000105: [ 8:C.ipt] Link down, terminating
N00000128: [ 1:main] Shutting down.
```

I am bit lost on what is still going wrong here, everything seems to be working except for the ipt part.

My MDT interface looks like below:

![Image](https://github.com/user-attachments/assets/4af3a93d-eba4-4271-9dc7-b87ed937ef47)
